version: "3.0"
services:
  mysql-db:
    container_name: vaccine-covid-19
    image: mysql
    ports:
      - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456Aa@
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456Aa@
      MYSQL_DATABASE: vaccine-covid-19

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456Aa@
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'