// Code generated by sqlc. DO NOT EDIT.
// source: clinic.sql

package db

import (
	"context"
)

const getClinic = `-- name: GetClinic :one
SELECT id, name, address, contact, location, status
FROM clinic
WHERE id = ? LIMIT 1
`

func (q *Queries) GetClinic(ctx context.Context, id string) (Clinic, error) {
	row := q.db.QueryRowContext(ctx, getClinic, id)
	var i Clinic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Contact,
		&i.Location,
		&i.Status,
	)
	return i, err
}
