// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Admin struct {
	ID       int32
	Username sql.NullString
	Password sql.NullString
}

type Booking struct {
	ID                sql.NullInt32
	CustomerID        int32
	DateRegistered    sql.NullTime
	DateBooked        sql.NullTime
	TimePeriod        sql.NullInt32
	DosesCompleted    sql.NullInt32
	VaccineName       sql.NullString
	ExtendedInterval  sql.NullInt32
	LotNumber         sql.NullString
	ClinicName        sql.NullString
	Price             sql.NullString
	SentReminderEmail sql.NullInt32
	DailyCapacityID   sql.NullInt32
	TotalBill         sql.NullString
	PaymentStatus     sql.NullBool
	StockItemID       sql.NullString
	DiscountID        int32
}

type Clinic struct {
	ID       string
	Name     sql.NullString
	Address  sql.NullString
	Contact  sql.NullString
	Location sql.NullString
	Status   sql.NullBool
}

type Constraint struct {
	ID              int32
	Code            string
	Description     sql.NullString
	VaccineEligible sql.NullBool
	NeedPrecaution  sql.NullBool
}

type Customer struct {
	ID              int32
	Email           sql.NullString
	Name            sql.NullString
	Address         sql.NullString
	Gender          sql.NullString
	Dob             sql.NullTime
	PhoneNumber     sql.NullString
	InsuranceNumber sql.NullString
	City            sql.NullString
	District        sql.NullString
	Commune         sql.NullString
	Ethnicity       sql.NullString
	Nationality     sql.NullString
}

type DailyCapacity struct {
	ID                int32
	ClinicID          sql.NullString
	MorningCapacity   sql.NullInt32
	AfternoonCapacity sql.NullInt32
	EveningCapacity   sql.NullInt32
	CurrentDate       sql.NullTime
}

type Discount struct {
	ID          sql.NullInt32
	Code        sql.NullString
	UsageCount  sql.NullInt32
	PriceRuleID int32
}

type MedicalCondition struct {
	ID              sql.NullInt32
	Code            string
	Description     sql.NullString
	ConditionStatus sql.NullBool
	CustomerID      int32
}

type PriceRule struct {
	ID              sql.NullInt32
	ProductID       string
	Value           sql.NullString
	ValueType       sql.NullInt32
	OncePerCustomer sql.NullBool
	UsageLimit      sql.NullInt32
	StartsAt        sql.NullTime
	EndsAt          sql.NullTime
	Title           sql.NullString
}

type Product struct {
	ID                    string
	Name                  sql.NullString
	Price                 sql.NullString
	Vendor                sql.NullString
	Sku                   sql.NullString
	VaccineType           sql.NullBool
	AuthorizedAges        sql.NullInt32
	Dose                  sql.NullString
	AntigenNature         sql.NullString
	RouteOfAdministration sql.NullString
	StorageRequirements   sql.NullString
	AvailableFormats      sql.NullString
	Diluent               sql.NullString
	Adjuvant              sql.NullString
	AlternateName         sql.NullString
	MinimumInterval       sql.NullInt32
	AuthorizedInterval    sql.NullInt32
	ExtendedInterval      sql.NullInt32
	Background            sql.NullString
	RegulatoryActions     sql.NullString
	SafetyStatus          sql.NullString
	AuthorizationStatus   sql.NullBool
	Trials                sql.NullString
	Distribution          sql.NullString
	Funding               sql.NullString
	Slug                  sql.NullString
	Image                 sql.NullString
	LotNumber             sql.NullString
	ExpiryDate            sql.NullTime
}

type ProductConstraint struct {
	ProductID    string
	ConstraintID int32
}

type StockItem struct {
	ID         string
	ClinicID   sql.NullString
	Quantity   sql.NullInt32
	Name       sql.NullString
	Price      sql.NullString
	LotNumber  sql.NullString
	ExpiryDate sql.NullTime
	ProductID  sql.NullString
}
