// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Admin struct {
	ID           int32
	Username     sql.NullString
	PasswordHash sql.NullString
}

type Booking struct {
	ID                sql.NullInt32
	CustomerID        int32
	DateRegistered    sql.NullTime
	DateBooked        sql.NullTime
	TimePeriod        sql.NullInt32
	DosesCompleted    sql.NullInt32
	VaccinePicked     sql.NullInt32
	ClinicName        sql.NullString
	SentReminderEmail sql.NullInt32
	DailyCapacityID   sql.NullInt32
	TotalBill         sql.NullString
	PaymentStatus     sql.NullBool
	ProductID         sql.NullString
	DiscountID        int32
}

type Clinic struct {
	ID       string
	Name     sql.NullString
	Address  sql.NullString
	Contact  sql.NullString
	Location sql.NullString
	Status   sql.NullBool
}

type ClinicProduct struct {
	ProductID string
	ClinicID  string
}

type Constraint struct {
	ID              int32
	Code            sql.NullString
	VaccineEligible sql.NullBool
	NeedPrecaution  sql.NullBool
}

type Customer struct {
	ID              int32
	Email           sql.NullString
	Name            sql.NullString
	Address         sql.NullString
	Gender          sql.NullString
	Dob             sql.NullTime
	PhoneNumber     sql.NullString
	InsuranceNumber sql.NullString
	City            sql.NullString
	District        sql.NullString
	Commune         sql.NullString
	Ethnicity       sql.NullString
	Nationality     sql.NullString
}

type DailyCapacity struct {
	ID                int32
	ClinicID          sql.NullString
	MorningCapacity   sql.NullInt32
	AfternoonCapacity sql.NullInt32
	EveningCapacity   sql.NullInt32
	CurrentDate       sql.NullTime
}

type Discount struct {
	ID          sql.NullInt32
	Code        sql.NullString
	UsageCount  sql.NullInt32
	PriceRuleID int32
}

type MedicalCondition struct {
	ID              int32
	Code            sql.NullString
	Description     sql.NullString
	ConditionStatus sql.NullBool
	CustomerID      int32
	ConstraintID    int32
}

type PriceRule struct {
	ID              sql.NullInt32
	ProductID       string
	Value           sql.NullString
	ValueType       sql.NullInt32
	OncePerCustomer sql.NullBool
	UsageLimit      sql.NullInt32
	StartsAt        sql.NullTime
	EndsAt          sql.NullTime
	Title           sql.NullString
}

type Product struct {
	ID                    string
	Price                 sql.NullString
	Sku                   sql.NullString
	VaccineType           sql.NullBool
	AuthorizedAges        sql.NullInt32
	Dose                  sql.NullString
	AntigenNature         sql.NullString
	RouteOfAdministration sql.NullString
	StorageRequirements   sql.NullString
	AvailableFormats      sql.NullString
	Diluent               sql.NullString
	Adjuvant              sql.NullString
	AlternateName         sql.NullString
	MinimumInterval       sql.NullString
	AuthorizedInterval    sql.NullString
	ExtendedInterval      sql.NullString
	Background            sql.NullString
	RegulatoryActions     sql.NullString
	SafetyStatus          sql.NullString
	AuthorizationStatus   sql.NullBool
	Trials                sql.NullString
	Distribution          sql.NullString
	Funding               sql.NullString
	Slug                  sql.NullString
	Image                 sql.NullString
	LotNumber             sql.NullString
	ExpiryDate            sql.NullTime
}

type ProductConstraint struct {
	ProductID    string
	ConstraintID int32
	Quantity     sql.NullInt32
}

type ProductVendor struct {
	VendorID  int32
	ProductID string
}

type Vendor struct {
	ID      int32
	Name    sql.NullString
	Contact sql.NullString
	Address sql.NullString
	Country sql.NullString
}
