// Code generated by sqlc. DO NOT EDIT.
// source: product.sql

package db

import (
	"context"
)

const getProduct = `-- name: GetProduct :one
SELECT id, price, sku, vaccine_type, authorized_ages, dose, antigen_nature, route_of_administration, storage_requirements, available_formats, diluent, adjuvant, alternate_name, minimum_interval, authorized_interval, extended_interval, background, regulatory_actions, safety_status, authorization_status, trials, distribution, funding, slug, image, lot_number, expiry_date
FROM product
WHERE id = ? LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Price,
		&i.Sku,
		&i.VaccineType,
		&i.AuthorizedAges,
		&i.Dose,
		&i.AntigenNature,
		&i.RouteOfAdministration,
		&i.StorageRequirements,
		&i.AvailableFormats,
		&i.Diluent,
		&i.Adjuvant,
		&i.AlternateName,
		&i.MinimumInterval,
		&i.AuthorizedInterval,
		&i.ExtendedInterval,
		&i.Background,
		&i.RegulatoryActions,
		&i.SafetyStatus,
		&i.AuthorizationStatus,
		&i.Trials,
		&i.Distribution,
		&i.Funding,
		&i.Slug,
		&i.Image,
		&i.LotNumber,
		&i.ExpiryDate,
	)
	return i, err
}
