// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	GetClinic(ctx context.Context, id string) (Clinic, error)
	GetProduct(ctx context.Context, id string) (Product, error)
}

var _ Querier = (*Queries)(nil)
