// Code generated by sqlc. DO NOT EDIT.
// source: stock-item.sql

package db

import (
	"context"
	"database/sql"
)

const updateStockItem = `-- name: UpdateStockItem :exec
UPDATE stock_item
SET
    quantity = ?,
    price = ?,
    lot_number = ?,
    expiry_date = ?
WHERE id = ?
`

type UpdateStockItemParams struct {
	Quantity   sql.NullInt32
	Price      sql.NullString
	LotNumber  sql.NullString
	ExpiryDate sql.NullTime
	ID         string
}

func (q *Queries) UpdateStockItem(ctx context.Context, arg UpdateStockItemParams) error {
	_, err := q.db.ExecContext(ctx, updateStockItem,
		arg.Quantity,
		arg.Price,
		arg.LotNumber,
		arg.ExpiryDate,
		arg.ID,
	)
	return err
}
