// Code generated by sqlc. DO NOT EDIT.
// source: vaccination.sql

package db

import (
	"context"
	"database/sql"
)

const getVaccination = `-- name: GetVaccination :one
SELECT doses_completed, vaccine_name, date_registered, clinic_name, date_booked
FROM booking
WHERE customer_id = ? limit 1
`

type GetVaccinationRow struct {
	DosesCompleted sql.NullInt32
	VaccineName    sql.NullString
	DateRegistered sql.NullTime
	ClinicName     sql.NullString
	DateBooked     sql.NullTime
}

func (q *Queries) GetVaccination(ctx context.Context, customerID int32) (GetVaccinationRow, error) {
	row := q.db.QueryRowContext(ctx, getVaccination, customerID)
	var i GetVaccinationRow
	err := row.Scan(
		&i.DosesCompleted,
		&i.VaccineName,
		&i.DateRegistered,
		&i.ClinicName,
		&i.DateBooked,
	)
	return i, err
}
