INSERT INTO `vaccine-covid-19`.product (id, name, price, vendor, vaccine_type, authorized_ages, dose, antigen_nature, route_of_administration, storage_requirements, available_formats, diluent, adjuvant, alternate_name, minimum_interval, authorized_interval, extended_interval, background, regulatory_actions, safety_status, authorization_status, trials, distribution, funding, slug, image, lot_number, expiry_date, immunization_schedule) VALUES ('3e397395-2331-4969-b3fe-825304a945df', 'Pfizer-BioNTech COVID-19 Vaccine', 20, 'Pfizer, BioNTech; Fosun Pharma', 'mRNA', 12, '0.5 mL (100 mcg of mRNA)', 'Transmembrane prefusion spike protein', 'IM', '-80°C to -60°C', 'Multi-dose vial (6 doses), preservative-free', 'YES', 'NONE', 'BNT162b2', 19, 21, 112, 'Comirnaty (formerly BNT162b2) is a nucleoside modified mRNA-based vaccine developed by BioNTech and Pfizer. Fosun Pharma has licensed Comirnaty in China. The vaccine is given as an intramuscular injection in two doses 21 days apart; some countries have modified that schedule. Comirnaty generates an immune response against SARS-CoV-2 by encoding a mutated form of the virus''s full spike protein.', '"On 31 December, WHO issued an emergency use validation for Comirnaty, which supports accelerated approval in other countries. Scores of countries have authorized or approved the vaccine for emergency use in adults; please see the Authorization/Approval column for hyperlinks to each individual country''s announcement. Countries noted below have expanded those authorizations/approvals to younger age groups.
- Australia: Provisional approval granted by TGA on 23 July for individuals 12 years and older.
- Brazil: Anvisa approved the vaccine in individuals 12 years and older on 11 June.
- Canada: On 5 May, authorization was expanded to include adolescents 12-15 years of age.
- EU: In addition to authorization for adults, the vaccine now has conditional marketing authorization by the EMA for use in adolescents aged 12-15 years.
- Malaysia: Approved for individuals 12 years and older on 15 June by the Drug Control Authority.
- Mexico: Approved by Cofepris for individuals 12 years and older.
- New Zealand: Approved for individuals 12 years and older by MedSafe.
- Philippines: EUA expanded on 28 May to include individuals 12 years and older.
- Singapore: Expanded emergency use to ages 12-15 years on 19 May.
- United Kingdom: Authorization for use expanded on 4 June to include individuals 12-15 years old.
- US: The FDA approved Comirnaty for use in individuals 16 years and older on 23 August. It was authorized (EUA) for adolescents 12-15 years old on 10 May; Pfizer and BioNTech plan to submit an EUA expansion for children 2-11 years old in September. A booster dose for certain immunocompromised individuals was authorized (EUA) on 12 August. On 18 August, HHS announced the US would start offering boosters to the public pending FDA review of safety and efficacy; Pfizer has initiated a rolling submission of a supplemental BLA. An FDA advisory committee meeting on a booster dose is scheduled for 17 September. The CDC recommends Comirnaty for people 16 years and older and recommends COVID-19 vaccines for pregnant people. "', 'EMA''s PRAC is currently reviewing safety concerns about Comirnaty for a number of adverse events.', 1, '"Pre-EUA trials:
Clinical trials evaluating Comirnaty include a pivotal Phase 2/3 trial of more than 43,000 healthy participants around the world (NCT04368728) published in NEJM, a Phase 2 trial of 960 participants in China in conjunction with Shanghai Fosun Pharmaceutical (NCT04649021), a Phase 1/2 trial in the US and Germany of 200 healthy participants between aged 18-55 years (NCT04380701), and a combined Phase 1/2 trial of 160 participants (NCT04588480) in Japan. Phase 3 data of 43,448 participants published in NEJM showed Comirnaty was 95% effective. Those results are backed up by Phase 1 data published in NEJM showing similar immunogenicity between Comirnaty and another BNT162 version developed by Pfizer and BioNTech, but fewer adverse effects were seen with Comirnaty.

Post-EUA trials:
The vaccine is being evaluated in additional trials including:
- Testing a booster vaccine for participants who received a vaccine dose 6-12 months ago to see how it fares against COVID-19 variants and a formulation of the vaccine that doesn''t require cold storage.
- Evaluating the vaccine in children under 12 years of age (NCT04816643).
- An NIH trial to examine whether vaccine recipients who are highly allergic are at greater risk for an allergic reaction to the vaccine (NCT04761822).
- An NIH trial to evaluate the safety and immunogenicity of a booster dose of the Moderna vaccine for individuals who got one dose of the Janssen vaccine, two doses of Comirnaty, or two doses of the Moderna vaccine (NCT04889209).
- MOMI-VAX, an NIH trial in people who are pregnant or postpartum.
- Pfizer is testing a third shot of Comirnaty together with their 20-valent pneumococcal conjugate vaccine.
- NIH is conducting trials to see how a third dose of an mRNA vaccine impacts individuals who were recipients of kidney transplants, and in patients with an autoimmune disease who did not respond to the 2-dose regimen (NCT05000216)

Evidence in new variants:
- B.1.1.7: Results from a pre-print posted to bioRxiv indicate Comirnaty is effective against the B.1.1.7 (Alpha) variant.
- B.1.351: In correspondence to the editor published in NEJM on 17 February, Comirnaty was approximately two-thirds less effective against the SARS-CoV-2 virus modified to have spike protein mutations similar to the B.1.351 (Beta) variant.
- B.1.1.7/B.1.351: In Qatar, researchers found the vaccine was 89.5% effective against the B.1.1.7 variant and 75.0% effective against the B.1.351 variant, according to correspondence published in NEJM.
- B.1.617.1: A preprint posted to bioRxiv showed the Pfizer vaccine neutralizes the B.1.617.1 (Kappa) variant, but that the variant is ""6.8-fold more resistant to neutralization by sera"" from the vaccine.
- B.1.526/B.1.429/B.1.1.7: Correspondence to the editor published in NEJMon 12 May indicates the Pfizer vaccine may the B.1.526 (Iota) and B.1.429 (Epsilon) variants as well as the B.1.1.7 variant carrying an E484K mutation.
- B.1.617.2: Two doses of Pfizer''s vaccine was 88% effective against the B.1.617.2 (Delta) variant, according to a study published in NEJM. However, a report from the Ministry of Health in Israel found the Pfizer vaccine was 64% effective at preventing infection against the B.1.617.2 variant.
- B.1.351/B.1.617.2: In July 2021, Pfizer and BioNTech announced data from a booster trial, which showed neutralization titers for the wild type and B.1.351 variant were 5-10 times higher if the booster was given at least 6 months after the second dose. The companies ""anticipate that a third dose will boost those antibody titers even higher"" for the B.1.617.2 variant than seen in a Nature study.

Asymptomatic transmission: A study by the Israeli Health Ministry found an 89.4% reduction in transmission for asymptomatic cases and 93.7% for symptomatic cases. A study published in NEJM of nearly 600,000 individuals from Clalit, a health maintenance organization covering about half the Israeli population, demonstrated results consistent with Phase 3 clinical trials.

Pregnancy: Preliminary findings published in NEJM show there are no ""obvious safety signals"" for patients who are pregnant and receive an mRNA vaccine.

In adolescents: In the study of adolescents ≥12 years old, the Pfizer vaccine had 100% efficacy, according to topline results announced by Pfizer on 31 March.

Previous COVID-19 history: Researchers at Icahn School of Medicine at Mount Sinai and Children’s Mercy Kansas City have published letters in NEJM that found a single dose of an mRNA vaccine in participants with a previous history of COVID-19 provides a similar or greater response compared with a two-dose regimen in participants without a COVID-19 history.

Heterologous vaccine schedule: Initial results from the COM-COV study, which is evaluating how patients fare after receiving doses of Vaxzevria and Comirnaty or vice versa, showed an increase in systemic reactogenicity compared with a two-dose series of Vaxzevria alone or Comirnaty alone. Results were published in The Lancet. Safety and immunogenicity data from COM-COV, posted to Pre-prints with The Lancet, ""support flexibility in the use of heterologous prime-boost vaccination"" for the AstraZeneca and Pfizer vaccines. For patients at an increased risk for thrombosis from an adenovirus-based vaccine, a heterologous prime-boost vaccine schedule with the Pfizer vaccine appears to be effective against COVID-19, according to correspondence published in The Lancet Infectious Diseases.

Boosters: Post-booster antibody response could be predicted by antibody levels after the first dose, according to a pre-print posted to medRxiv. A third shot of the Pfizer vaccine increased the marginal effectiveness of the vaccine by 70-84% between 14 and 20 days after the dose, according to a pre-print posted to medRxiv.

Testing dosing intervals:
- Neutralizing antibody levels appear to be higher in individuals who received the second dose of the Pfizer vaccine between 6-14 weeks after the first dose compared with 21 days, according to a pre-print posted to Cell Press Sneak Peek.

Anaphylaxis:
- For individuals who experienced an immediate allergic reaction to the first dose, all tolerated the second dose after being pretreated with antihistamine medication, according to a study published in JAMA Internal Medicine."', '" Africa: The African Union has purchased 270 million total doses of the vaccines made by AstraZeneca, Pfizer, and Janssen, but it is not clear how many doses purchased were of the Pfizer vaccine.
- Australia: The country has ordered 20 million total doses and expects to begin vaccinating people at the end of February.
- Brazil: Pfizer has reached a deal to provide 100 million doses to the country. An additional 100 million doses were purchased on 11 May.
- Canada: Canada reached an initial agreement for up to 76 million; another 20 million doses were ordered on 12 January.
- China: Fosun Pharma has agreed to purchase 100 million doses for China for 2021, pending the vaccine''s approval.
- Costa Rica: The companies have signed an agreement with Costa Rica to provide 3 million doses.
- EU: In November, the companies agreed to supply the EU and its eligible Member States with 200 million doses with the option to acquire 100 million doses at a later date. On 17 February, Pfizer and BioNTech announced they have reached an agreement to supply another 200 million doses to EU Member States. On 19 April, they announced they would supply the EU with another 100 million doses, bringing the total vaccine doses available for purchase to 600 million. Sanofi is helping to supply over 125 million vaccine doses to the EU, manufacturing the vaccine in an agreement with BioNTech. The EU is also working to secure additional doses of the vaccine, for a total of 1.8 billion doses by the end of 2023.
- Germany: The German government reportedly secured 30 million doses of Comirnaty for its country in addition to what has been secured by the EU, according to Reuters.
- Hong Kong, Macao: Pfizer and BioNTech also have tentative agreements to supply 10 million vaccine doses to Hong Kong and Macao.
- India: Pfizer has been discussing supplying India with Comirnaty and has indicated it will prioritize orders from the government.
- Japan: Pfizer and BioNTech have agreed to supply the country with 144 million vaccines.
- Jordan: Pfizer and BioNTech have reached an agreement with Jordan for 3 million doses.
- Lebanon: The caretaker health minister of Lebanon has signed an agreement for 2.1 million doses of Pfizer and BioNTech''s vaccine to be delivered in February.
- Malaysia: A total of 25 million vaccines have been ordered.
- Mexico: In December, Mexico reached a deal with Pfizer and BioNTech for 34.4 million doses of the vaccine.
- New Zealand: On 5 March, the prime minister of New Zealand announced they would purchase 8.5 million doses, bringing their total Pfizer doses to 10 million.
- South Korea: The country initially ordered 6 million vaccine doses from Pfizer and BioNTech for the second quarter of 2021. On 24 April, South Korea reached an agreement to purchase another 40 million vaccine doses from Pfizer.
- Switzerland: The country has reached an agreement for 3 million doses.
- US: The companies reached an agreement with the US government under OWS in July 2020 for 100 million doses of the vaccine in 2021; the government has the option to acquire another 500 million vaccine doses at a later date. On 23 December 2020, the US Department of Health and Human Services and Department of Defense purchased another 100 million doses; they purchased 100 million additional doses on 11 February and 200 million more doses on 23 July. On 2 August, the US Department of Defense announced it had purchased 500 million doses of Comirnaty for COVAX."', 'Fosun Pharma has invested $135 million with BioNTech, and another $50 million in exchange for 1.58 million shares. The German government gave BioNTech €375 million ($445 million towards its COVID-19 vaccine program, while the European Commission and European Investment Bank have invested €100 million ($119 million) in BioNTech''s vaccine program. While Pfizer and BioNTech did not take development funding from OWS, $6 billion from OWS were used to purchase vaccine doses from Pfizer in July 2020, December 2020, and February 2021, with $1.95 billion to be paid after the delivery of the first 100 million vaccine doses.', 'pfizer', 'https://cloudfront-us-east-2.images.arcpublishing.com/reuters/GEPFXZLGLVLEZGNG2EVPESEROI.jpg', 'PFI001', '2021-12-31', 2);
INSERT INTO `vaccine-covid-19`.product (id, name, price, vendor, vaccine_type, authorized_ages, dose, antigen_nature, route_of_administration, storage_requirements, available_formats, diluent, adjuvant, alternate_name, minimum_interval, authorized_interval, extended_interval, background, regulatory_actions, safety_status, authorization_status, trials, distribution, funding, slug, image, lot_number, expiry_date, immunization_schedule) VALUES ('d28a51c1-15f2-4826-8684-185773bf1e47', 'Moderna COVID-19 Vaccine', 25, 'Moderna, BARDA, NIAID', 'mRNA', 18, '0.5 mL (100 mcg of mRNA)', 'Transmembrane prefusion spike protein', 'IM', '-25°C to -15°C', 'Multi-dose vial (6 doses), preservative-free', 'NO', 'NONE', 'mRNA-1273', 21, 28, 112, 'Moderna COVID‑19 Vaccine (formerly known as mRNA-1273) is based on prior studies of related coronaviruses. It is a two-dose mRNA vaccine given 28 days apart. It is known as Spikevax in Europe, TAK-919 in Japan, and Elasomeran in Australia.', '" WHO: Emergency use listing (EUL) granted 30 April 2021. Many countries have authorized or approved the vaccine for emergency use, and some countries are beginning to expand its use to younger patients. Please see the Authorization/Approval column for hyperlinks to each individual country''s announcement.

- Australia: Provisionally approved by TGA for individuals 12 years and older.
- Canada: On 3 March, the NACI recommended a 4-month interval between doses is appropriate in the context of limited availability. The same day, Health Canada and EMA published the vaccine''s full clinical data package. Moderna has filed for authorization of its vaccine for adolescents in Canada.
- EU: EMA’s safety committee (PRAC) is currently reviewing the Moderna vaccine for unusual blood clots with low platelets and myocarditis. EMA extended the indication for Spikevax to individuals aged 12-17 years on 23 July.
- Switzerland: Approved by Swissmedic in adolescents 12-17 years of age.
- UK: Approved for adolescents 12-17 years of age by MHRA.
- US: EUA issued 18 December for patients 18 years and older. Moderna has applied to extend the EUA to adolescents 12-17 years of age. On 01 April, the FDA revised the EUA to increase the number of vaccine doses available in each vial and authorize a 15-dose vial. Moderna initiated the rolling BLA submission on 01 June. Pregnant individuals should receive a COVID-19 vaccine according to a CDC  recommendation. A booster dose has been authorized (EUA) for immunocompromised individuals was authorized 12 August and recommended by the CDC the next day. On 18 August, HHS announced that the US would start offering boosters to the public pending FDA review of safety and efficacy."', 'EMA''s PRAC is currently investigating Moderna''s vaccine for safety concerns of erythema multiforme, glomerulonephritis and nephrotic syndrome, and menstrual disorders. ', 1, '"Pre-EUA trials:
- In the pivotal Phase 3 trial of 30,000 participants at high risk for COVID-19, participants received a 100 µg dose of the Moderna COVID‑19 Vaccine and another 4 weeks later or placebo injections and then be followed for up to 2 years; results published in NEJM demonstrated efficacy of 94.1% (COVE trial; NCT04470427). Final efficacy in COVE was 93%, and immunity persisted for at least 6 months, according to a press release. Moderna posted the full trial protocol for COVE on 17 September.
- A Phase 2 dose-confirmation trial of 600 healthy participants was completed (NCT04405076); preliminary results from that study published in Vaccine showed patients in the 50 and 100 ug groups demonstrated ""significant immune responses"" to COVID-19.
- A Phase 1 trial (NCT04283461) of 105 healthy participants provided the basis for Moderna’s investigational new drug application (IND), which set the stage for Phase 2 testing.

Post-EUA trials:
- Initial analysis of an ongoing Phase 2/3 trial (NCT04649151) testing Moderna''s vaccine in 3,225 adolescents aged 12-18 years showed an efficacy rate of 96% in teens without prior COVID-19 who received at least one injection, according to a statement.
- NIH began a trial in April to examine whether vaccine recipients who are highly allergic are at greater risk for an allergic reaction to the vaccine (NCT04761822).
- Another NIH trial is evaluating the safety and immunogenicity of a booster dose of the Moderna vaccine for individuals who got one dose of the Janssen vaccine, two doses of Comirnaty or two doses of the Moderna vaccine (NCT04889209).
- A third NIH study, MOMI-VAX, is testing the vaccine in women who are pregnant or postpartum.
- A next-generation version of Moderna COVID-19 Vaccine that is refrigeration stable, named mRNA-1283, is currently being evaluated in a Phase 1 study.
- In March, Moderna and NIAID began evaluating a version of the vaccine, called mRNA-1273.351, that was designed to protect against the B.351 (Beta) variant (NCT04785144).
- NIH is conducting trials to see how a third dose of an mRNA vaccine impacts individuals who were recipients of kidney transplants, and for patients with autoimmune disorders who did not respond to the 2-dose vaccine regimen (NCT05000216).

Real-world evidence:
Real-world data, published in CDC''s MMWR, showed the Moderna vaccine was 80% effective 14 days after the first dose and 90% effective 14 days after the second dose. The durability of response seems to persist to at least 6 months, according to correspondence to the editor published in NEJM.

Effectiveness against variants: In correspondence to the editor published in NEJM, investigators from Moderna and NIAID noted the protective effect of the vaccine against the B.1.351 (Beta) variant was inconclusive and ""remains to be determined."" Another correspondence to the editor from NEJM suggests the Moderna vaccine may be effective against B.1.429 (Epsilon) but less effective against B.1.351 (Beta). Non-peer-reviewed data posted to MedRxiv and released by Moderna showed the mRNA-1273.351 booster vaccine induces neutralizing titers against SARS-CoV-2, B.1.351 (Beta), and P.1 (Gamma). A pre-print posted to bioRxiv showed the Moderna vaccine neutralizes the B.1.617.1 (Kappa) variant, but the variant is ""6.8-fold more resistant to neutralization by sera"" from the vaccine. Moderna announced on 29 June that Moderna is effective against both the B.1.617.1 (Kappa) and B.1.617.2. (Delta) variants based on results from a lab study.

Previous COVID-19 history: A paper published in NEJM found a single dose of an mRNA vaccine in participants with a previous history of COVID-19 provides a similar or greater response compared with a two-dose regimen in participants without a COVID-19 history.

Healthcare workers: Among healthcare workers in California vaccinated with the Pfizer and Moderna vaccines, the number of new COVID-19 cases was deemed ""rare,"" according to correspondence to the editor published in NEJM. A real-world assessment of mRNA vaccines published in NEJM showed the Pfizer and Moderna vaccines had an adjusted efficacy of 91% for healthcare workers who were fully vaccinated and 81% for those partially vaccinated.

Pregnancy: No ""obvious safety signals"" were observed in pregnant patients who received an mRNA vaccine, according to preliminary findings published in NEJM.

Anaphylaxis: Among patients who experienced anaphylaxis to the first dose of the vaccine, all patients tolerated the second dose after being pretreating with an antihistamine, according to a study published in JAMA Internal Medicine."', '"- Australia: The Australian government has ordered 10 million doses of the legacy Moderna vaccine and 15 million doses of the booster pending the vaccine''s approval in the country.
- Canada: Canada''s government has ordered 40 million doses of the vaccine with the option to purchase 16 million more doses.
- Colombia: The country has reached an agreement for 10 million doses of the vaccine.
- EU: The European Commission has ordered 160 million doses from Moderna and added 300 million more on 17 February. On 22 June, the European Commission exercised its option to purchase another 150 million vaccine doses for 2022.
- Israel: The Ministry of Health of Israel has ordered 6 million doses of the vaccine.
- Japan: The Ministry of Health, Labour and Welfare of Japan (MHLW) and Takeda Pharmaceuticals have reached an agreement with Moderna for 50 million vaccine doses. An additional 50 million vaccines to be delivered in 2022 were announced by Takeda on 20 July 2021.
- Philippines: An agreement to supply 20 million doses of the Moderna vaccine to the Philippines has been reached in addition to purchases of other vaccines from AstraZeneca, Sinovac, and Novavax.
- Qatar, Singapore: Both Qatar and Singapore have agreed to purchase an undisclosed number of vaccine doses.
- South Korea: Moderna has agreed to supply 40 million doses of the vaccine to South Korea.
- Switzerland: The Swiss government has ordered 7.5 million vaccine doses from Moderna, with delivering pending regulatory approval in the country. As of 3 February, the Swiss government ordered another 6 million vaccine doses from Moderna.
- Taiwan: In an announcement, Moderna said it would supply Taiwan with 5 million doses pending approval of the vaccine.
- UK: The UK government has ordered 7 million doses of Moderna''s vaccine.
- US: The United States government initially agreed to purchase 100 million doses of the vaccine, and another 100 million doses were ordered on 11 December. On 11 February, the US Department of Health and Human Services and Department of Defense purchased an extra 100 million doses of Moderna''s vaccine. The government ordered another 200 million doses of the vaccine on 16 June, bringing the total US vaccine order to 500 million doses. Sanofi has pledged to help Moderna fulfill its vaccine supply obligations in the US."', 'The Moderna COVID‑19 Vaccine is funded by OWS and in collaboration with NIAID for the Phase 3 COVE study. Approximately $5.3 billion has been allocated to Moderna under OWS. BARDA has awarded $955 million to Moderna for their vaccine, including $483 million for initial clinical development and another $472 million for late-stage clinical development. On 18 April, Moderna disclosed an amendment to the BARDA agreement worth an additional $236 million. A smaller amount from DARPA, $56 million, is not strictly for the Moderna COVID‑19 Vaccine but was awarded for "development of a mobile manufacturing prototype leveraging Moderna’s existing manufacturing technology that is capable of rapidly producing vaccines and therapeutics." In a preliminary report of the vaccine published in NEJM, the authors recognized support from Emory University, Vanderbilt University Medical Center, the Dolly Parton COVID-19 Research Fund.', 'moderna', 'https://s3-ap-northeast-1.amazonaws.com/psh-ex-ftnikkei-3937bb4/images/9/3/5/5/31315539-3-eng-GB/Cropped-16083390922020-12-17T162026Z_1575076929_RC24PK9L41HN_RTRMADP_3_HEALTH-CORONAVIRUS-VACCINES-MODERNA.JPG', 'MOD001', '2021-12-31', 2);
INSERT INTO `vaccine-covid-19`.product (id, name, price, vendor, vaccine_type, authorized_ages, dose, antigen_nature, route_of_administration, storage_requirements, available_formats, diluent, adjuvant, alternate_name, minimum_interval, authorized_interval, extended_interval, background, regulatory_actions, safety_status, authorization_status, trials, distribution, funding, slug, image, lot_number, expiry_date, immunization_schedule) VALUES ('675e3217-048d-4d22-ba2b-14ef069f63f6', 'AstraZeneca COVID-19 / COVISHIELD Vaccine', 3, 'BARDA, OWS', 'Non-replicating viral vector (ChAd)', 18, '0.5 mL (5 x 1010 viral particles)', 'Transmembrane spike protein', 'IM', '2ºC to +8ºC', 'Multi-dose vial (8-and 10-dose presentations), preservative-free', 'NO', 'NONE', 'AZD1222; also known as Vaxzevria', 28, 84, 112, 'AstraZeneca and the Oxford Vaccine Group at the University of Oxford have developed COVID-19 Vaccine AstraZeneca (Vaxzevria in Europe; previously AZD1222 and ChAdOx1), a chimpanzee adenovirus vaccine. In India, it is jointly developed by the Serum Institute of India and AstraZeneca and goes by the name Covishield. The vaccine is administered in two doses, between 4-12 weeks apart, although there is evidence of an antibody response for a second dose or a third booster dose spread out to 46 weeks apart.', '"A WHO panel recommended the use of the vaccine for all adults on 10 February; versions of the vaccine produced by South Korea and the Serum Institute of India were given an emergency use listing (EUL) on 15 February.

- Brazil: On 29 January, AstraZeneca submitted the vaccine for full regulatory approval.
- European Union: EMA''s safety committee (PRAC) is currently reviewing post-vaccination cases of Guillain-Barre syndrome.
- Japan: Submitted for approval by AstraZeneca on 5 February.
- South Africa: Authorized for emergency use by SAHPRA on 27 January; vaccine use was halted following data that it inadequately protects against the B.1.351 (Beta) variant. On 21 March, South Africa completed the sale of its remaining doses of the AstraZeneca vaccine to other member states in the African Union.

Over 130 countries have currently authorized or approved the AstraZeneca vaccine for emergency use. Please see the Authorization/Approval column for hyperlinks to each individual country''s announcement."', 'Very rare side effects have been reported after some individuals have taken the AstraZeneca vaccine, which include blood clotting issues (TTS syndrome), thrombotic events, capillary leak syndrome, and Guillain-Barre syndrome. ', 1, '"Pre EUA trials:
- A Phase 3 trial of over 32,000 participants (NCT04516746). AstraZeneca released the trial''s clinical study protocol. Interim safety and efficacy data released by AstraZeneca indicated the vaccine was 79% effective at preventing COVID-19 and fully protective against severe/critical disease and hospitalization. Following criticism from US health officials that the data presented might be outdated, AstraZeneca released new results that added 49 new cases of COVID-19 to the analysis, reducing the effectiveness of the vaccine to 76% with 100% effectiveness against severe disease and hospitalization.
- A Phase 2/3 trial (COV002) conducted by the University of Oxford of up to 12,390 participants is active and currently recruiting (NCT04400838).
- A Phase 1/2 (NCT04324606) single-blinded, multi-center study (COV001) of 1,090 healthy adult volunteers aged 18-55 years with four treatment arms, and a Phase 1/2 trial of healthy participants in South Africa (NCT04444674) are both active but not recruiting.

Post EUA trials:
- An inhaled version of the vaccine candidate is being tested in a small trial of 30 people.
- In the UK, a Phase 2 trial of the vaccine in children and young adults is underway.
- In several countries, a trial combining the Sputnik V and AstraZeneca vaccines is planned. In Russia, this trial has been paused prior to approval while the Russian health ministry''s ethical committee seeks more data.
- In June 2021, AstraZeneca began testing AZD2816, a COVID-19 vaccine specifically tailored to combat the B.1.351 (Beta) variant, in a Phase 2/3 trial.
- The Indian Council of Medical Research has approved a study that will vaccinate individuals in India with Covaxin and AstraZeneca''s vaccine.

Interim data from a Phase 3 trial in the UK, Brazil, and South Africa published in The Lancet indicate the vaccine has overall efficacy of 70%, with vaccine efficacy at 62.1% in a group of participants receiving two standard doses and 90% in a group receiving one-half dose followed by a standard dose. Phase 2/3 COV002 trial published in The Lancet showed the vaccine candidate has similar immunogenicity in patients of all ages but appears to be better tolerated in older adults. In a pre-print with The Lancet, researchers found the AstraZeneca had a 76% efficacy for up to 90 days after the first dose. Initial results from the COM-COV study, which is evaluating how patients fare after receiving doses of Vaxzevria and the Pfizer vaccine Comirnaty or vice versa, showed an increase in systemic reactogenicity compared with a two-dose series of Vaxzevria alone or Comirnaty alone; results were published in The Lancet. Further results from the AstraZeneca/Pfizer vaccine mixing trial ""support flexibility in the use of heterologous prime-boost vaccination using ChAd and BNT COVID-19 vaccines,"" according to a paper posted to Pre-prints with The Lancet.

Real-world evidence:
Results of a study published in The Lancet from researchers at the University of Edinburgh, the University of Strathclyde and Public Health Scotland indicate that the AstraZeneca vaccine reduces hospitalizations by 94% between 28-34 days after the first dose.

Evidence in new variants:
A paper examining the AstraZeneca vaccine and the B.1.1.7 (Alpha) variant, also published in The Lancet, showed the vaccine had reduced effectiveness against the new variant compared with SARS-CoV-2. A study published in NEJM on 16 March showed the vaccine is not effective against the B.1.351 (Beta) variant. When tested against the B.1.617.2 (Delta) variant, the a full course of the AstraZeneca vaccine was 67% effective in preventing COVID-19 and 92% effective against hospitalization, according to a paper published in NEJM.

Boosters:
The antibody response from the first dose of the vaccine does not appear to predict the antibody response from the third dose, according to a paper posted to medRxiv. An individual who started an AstraZeneca vaccine dose series and then received the Pfizer vaccine as a booster had ""striking increase of vaccine-induced SARS-CoV-2 surrogate neutralisation activity"" according to a paper published in The Lancet Infectious Diseases.

People living with HIV:
The AstraZeneca vaccine is safe and generates an immune response for people living with HIV, according to a study published in The Lancet HIV."', '"- Africa: The African Union has purchased 270 million total doses of the vaccines made by AstraZeneca, Pfizer, and Janssen, but it is not clear how many doses purchased were of the AstraZeneca vaccine. An additional 400 million doses were secured on 28 January.
- Canada: Health Canada has ordered 20 million doses of the vaccine, with 30 million expected to be available by March. Verity Pharmaceuticals and Serum Institute of India have applied to provide the India-produced version of AstraZeneca''s vaccine, COVI-SHIELD, to Canada to ease shortages.
- COVAX: The initiative COVAX has purchased 300 million initial doses of the vaccine and will purchase 100 million doses of either the AstraZeneca or Novavax vaccine through a grant from the Bill & Melinda Gates Foundation.
- European Union: Through the Inclusive Vaccine Alliance in Europe, AstraZeneca is supplying up to 400 million vaccine doses to member states of the European Union.
- India: Under the name Covishield, India has ordered approximately 21 million doses of the vaccine.
- Indonesia: Expected to receive up to 23.1 million doses of the vaccine through COVAX.
- Mali: The country intends to purchase 8.4 million doses of the vaccine.
- Morocco: Morocco has purchased 25 million vaccine doses from the Serum Institute of India.
- North Korea: COVAX is providing up to 2 million doses of the vaccine to North Korea.
- Saudi Arabia: An agreement for 3 million doses of the vaccine has been reached with the Serum Institute of India.
- Serum Institute of India: AstraZeneca is working with the Serum Institute of India to supply 1 billion vaccine doses to India and low- and middle-income countries.
- South Africa: The Serum Institute of India is supplying South Africa with 1.5 million doses of the vaccine.
- South Korea: AstraZeneca has agreed to supply South Korea with 20 million doses of the vaccine.
- Switzerland: AstraZeneca has reached an agreement with Switzerland to supply up to 5.3 million vaccine doses.
- US: Under OWS, the US has purchased 300 million doses of the vaccine. On 26 April, the White House announced the US would share its AstraZeneca stock with other countries."', 'The AstraZeneca trials are funded in part by BARDA and OWS. OWS has allocated $1.6 billion for AstraZeneca, which includes $1.2 billion for 300 million doses of the vaccine and as well as research and clinical testing.', 'astra-zeneca', 'https://cdn.vox-cdn.com/thumbor/c0bhhB_jTZltCy3ITS8x6t5uUU8=/1400x1050/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/22292400/1301049483.jpg', 'AST001', '2021-12-31', 2);
INSERT INTO `vaccine-covid-19`.product (id, name, price, vendor, vaccine_type, authorized_ages, dose, antigen_nature, route_of_administration, storage_requirements, available_formats, diluent, adjuvant, alternate_name, minimum_interval, authorized_interval, extended_interval, background, regulatory_actions, safety_status, authorization_status, trials, distribution, funding, slug, image, lot_number, expiry_date, immunization_schedule) VALUES ('acc496ab-fb8c-4d43-99e4-b28f5ddf1d16', 'Janssen COVID-19 Vaccine', 10, 'Janssen Vaccines (Johnson & Johnson)', 'Non-replicating viral vector (Ad26)', 18, '0.5 mL (5 x 1010 viral particles)', 'Transmembrane prefusion spike protein', 'IM', '2ºC to +8ºC', 'Multi-dose vial (5 doses), preservative-free', 'NO', 'NONE', 'JNJ-78436735; Ad26.COV2.S', 0, 0, 0, 'Janssen Biotech, a company owned by Johnson & Johnson, has developed COVID-19 Vaccine Janssen (formerly JNJ-78436735 and Ad26.COV2.S), a single-dose COVID-19 vaccine, using their AdVac and PER.C6 systems, which were also used to develop the company''s Ebola vaccine. COVID-19 Vaccine Janssen is a part of Operation Warp Speed.', '"- WHO: Listed the vaccine for emergency use and for COVAX rollout. WHO also released interim guidance for use of the vaccine on 17 March. The CDC has stated the vaccine is safe for pregnant women.

Many countries have authorized or approved the Janssen vaccine for emergency use."', 'EMA''s PRAC is currently assessing safety issues for the Janssen vaccine concerning Guillain-Barré syndrome, immune thrombocytopenia, dizziness and tinnitus, and menstrual disorders. ', 1, '"Janssen has tested the vaccine in several trials:
- The international Phase 3 ENSEMBLE trial (NCT04505722) (ENSEMBLE Study Protocol)
- The Phase 3 two-dose test of JNJ-78436735 called ENSEMBLE 2 (NCT04614948)
- A randomized, double-blind, placebo-controlled, international Phase 1/2 study of a 2-dose regimen (NCT04436276)
- A dose- and range-finding study that was expanded in April 2021 to include adolescents (NCT04535453)
- An NIH trial is evaluating the safety and immunogenicity of a booster dose of the Moderna vaccine for individuals who got one dose of the Janssen vaccine, two doses of the Pfizer vaccine or two doses of the Moderna vaccine (NCT04889209); another NIH trial is investigating an extra dose for patients with an autoimmune disorder who did not response to the original COVID-19 vaccine regime (NCT05000216).
- A third NIH trial, MOMI-VAX, is testing the vaccine in women who are pregnant or postpartum.
- A Phase 1 trial in Japan (NCT04509947).
- J&J is also seeking approval of a Phase 3 trial in India.
- The Phase 3 open-label Sisonke (Together) trial (NCT04838795).

In topline Phase 3 data from 43,783 participants announced by press release on 29 January, the company said the vaccine was 66% effective overall, with 72% protection against moderate or severe disease in the United States, 66% in Latin America, and 57% in South Africa. Documents released ahead of the 26 February VRBPAC meeting indicate the vaccine decreases asymptomatic transmission of SARS-CoV-2 by 74%. Results from the Phase 1/2a study in humans published in NEJM found a single dose of the vaccine showed immunogenicity and a good safety profile, with 90% of participants developing neutralizing-antibody titers against wild-type virus 29 days after receiving the vaccine. Data from the ENSEMBLE trial were published in NEJM, which showed vaccine efficacy was 66.9% at 14 days and 66.1% at 28 days; the vaccine was also effective against severe disease (76.7%, 14 days; 85.4%; 28 days). A study of real-world effectiveness of the Janssen vaccine, posted to the pre-print server medRxiv, indicated the vaccine was 76.7% effective.

Evidence in new variants:
In July 2021, J&J announced the vaccine ""elicited neutralizing antibody activity"" against the B.1.617.2 (Delta) variant in 8 patients from the ENSEMBLE study. A study published in NEJM, which affirmed the durable humoral and cellular response of the vaccine at 8 months, also appeared to show the vaccine has a growing response to SARS-CoV-2 variants over that period of time. Results from the Sisonke trial in South Africa show the Janssen vaccine is 71% effective against the B.1.617 variant. However, a pre-print posted to bioRxiv suggested the Janssen vaccine has low neutralizing titer against the B.1.351 (Beta), B.1.617.2, B.1.617.2 + AY.1 (Delta Plus), and C.37 (Lambda) variants.

Boosters:
- Initial results from patients in two Phase 1/2a clinical trials appears to show ""robust immune memory"" in patients who received a booster dose of the Janssen vaccine at 6 months, according to a pre-print posted to medRxiv."', '"J&J has a memorandum of understanding to provide 500 million vaccine doses to COVAX, and has also agreed to provide 500 million vaccines to Gavi, The Vaccine Alliance. Sanofi has promised manufacturing support to J&J for the production of the vaccine after announcing a similar agreement with Pfizer and BioNTech. Merck has also said it will help produce the vaccine. On 15 March, IDT Biologica said it would use the capacity reserved for Takeda''s COVID-19 vaccine candidate to help produce COVID-19 Vaccine Janssen. On 18 May, Biological E announced it would produce COVID-19 Vaccine Janssen alongside its own COVID-19 vaccine candidate.
- African Union: J&J has announced it will provide approximately 400 million doses of their vaccine to the African Union.
- European Union: The European Commission has reached an agreement with J&J for 200 million doses, with the option to purchase another 200 million doses. In June, the European Commission ordered another 40 million doses, according to a spokesperson.
- Gavi, the Vaccine Alliance: The alliance has agreed to purchase 200 million doses of the Janssen vaccine.
- South Africa: The country and J&J have reached an agreement for 11 million doses of the vaccine.
- UK: The company has agreed to supply 30 million doses, with the option to purchase an additional 22 million.
- US: A total of 20 million doses were to be shipped to local governments and other vaccinators in March, according to J&J. The company has an agreement with the Department of Health and Human Services and the Department of Defense to provide 100 million vaccine doses. On 10 March, President Biden announced that the US would order another 100 million doses of the vaccine."', 'COVID-19 Vaccine Janssen is funded by Janssen, BARDA, NIAID, and Operation Warp Speed. OWS has allocated $2.1 billion to Janssen under the DOD and HHS partnership. In partnership with BARDA, Janssen has committed to investing more than $1 billion in vaccine research and development.', 'johnson', 'https://ktla.com/wp-content/uploads/sites/4/2021/04/6f92023a25424d8a82f4be92fdfad44c.jpg?w=2560&h=1440&crop=1', 'JOH001', '2021-12-31', 1);
